### ISSUE TITLE
Can't PIP install 

### ISSUE THREAD

**Issue by marrabld** [AutomatedFishID/emtmlibpy#4]
error complaining that "src" was not found. I believe this is past the point where pip is looking for the pyproject.toml and most likely originates from [this](https://github.com/AutomatedFishID/emtmlibpy/blob/c3397e177578493f8640f2eef99aff57812d4a8b/src/setup.cfg#L17) line within it. The problem might be related to the fact that the "#subdirectory=src" appears to be required for pip to find the pyproject.toml when reading from git and I'm guessing that might result in an effective difference in working directory with regards to the environment you were using?

**Comment by nikoder** [comment]
I take it this reproduces for you and isn't just a quirk of my pip version or something like that?

**Comment by marrabld** [comment]
Im just taking a look now.   looks like a typo from me.   I'll fix and make a pull request for you to test.
